# Configuração do Banco de Dados H2 (Em Memória)
spring.datasource.url=jdbc:h2:mem:hermesdb;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Hibernate / JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false

# Ativar Console do H2 (Opcional - Acessível via navegador se necessário)
spring.h2.console.enabled=true
